branches:
  - '+([0-9])?(.{+([0-9]),x}).x'
  - 'main'

  - name: 'next'
    prerelease: true

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/github"
    - assets:
      - "cucumber-js-test-runner-*.visx"
  - - "@semantic-release/npm"
    - npmPublish: false
  - - "@semantic-release/changelog"
    - assets:
      - CHANGELOG.md
  - - "@semantic-release/git"
    - assets:
      - CHANGELOG.md
      - package.json
      - package-lock.json
