name: Pull Request

on:
  pull_request:
    branches:
      - main
      - next

jobs:
  compile_and_lint:
    name: Compile and lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure NodeJS
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'

    - run: npm ci
    - run: npm run compile