name: Release
on:
  push:
    branches:
      - main
      - next

jobs:
  compile_and_lint:
    name: Compile and lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure NodeJS
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
        cache: npm
    
    - run: npm ci
    - run: npm run package

    - name: Semantic Release
      id: semantic
      uses: cycjimmy/semantic-release-action@v3
      with:
        extra_plugins: |
          @semantic-release/npm@9
          @semantic-release/changelog
          @semantic-release/git
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
